### ISSUE TITLE
使用sniffer的一些问题，谢谢回答。

### ISSUE THREAD

**Issue by virtowlee** [HatBoy/python-sniffer#1]
⑴我在windows7下运行您的代码，双击抓取的数据包info栏，无法展示数据包详情。
⑵运行时，筛选程序如何起作用，我输入筛选条件：TCP，没有反应。
谢谢！

**Comment by HatBoy** [comment]
您好，本程序的核心是scapy库，没有在windows下面进行测试，测试环境是Ubuntu `python2.7，对于双击数据包栏目没有数据包详情，这是一个已知的bug，第一次双击会显示上一次双击的数据，也就是说，如果想要看到数据包详情，需要双击栏目，然后关关闭，在重新双击该栏目就会有数据包详情了，至于问题二，我没有实现过滤功能，只留下了接口，没有实现内容，具体实现方法是使用scapy库的snifer()函数的过滤功能。

**Comment by virtowlee** [comment]
好的，谢谢！
